task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/kyc/project/RT-DETR/data/coco2017_50/train2017/
    ann_file: /home/kyc/project/RT-DETR/data/coco2017_50/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 0
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/kyc/project/RT-DETR/data/coco2017_50/val2017/
    ann_file: /home/kyc/project/RT-DETR/data/coco2017_50/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2
  num_workers: 0
  drop_last: False
