task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: data/coco/val2017
    ann_file: data/coco/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 0
  drop_last: True
  subset_size: 100

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: data/coco/val2017
    ann_file: data/coco/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  batch_size: 2
  num_workers: 0
  drop_last: False