__include__: [
  '../dataset/coco_50_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

output_dir: /home/kyc/project/RT-DETR/results/pytorch_training/rtdetr_r50vd_50img_50epoch

# 修改训练轮数为50
epochs: 50

# 修改学习率调度
lr_scheduler:
  type: MultiStepLR
  milestones: [40]
  gamma: 0.1

# 修改优化器设置
optimizer:
  type: AdamW
  params: 
    lr: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 0.0001

# 修改数据加载器设置
train_dataloader: 
  batch_size: 1  # 减少批次大小避免内存不足
  num_workers: 0

val_dataloader:
  batch_size: 1
  num_workers: 0

# 添加日志设置
print_freq: 1
save_freq: 10
