# RT-DETR R50 6x COCO配置文件
task: detection

model: RTDETR
criterion: SetCriterion
postprocessor: RTDETRPostProcessor

# 模型配置
RTDETR:
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
  multi_scale: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]

# 骨干网络配置
PResNet:
  depth: 18
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True

# 编码器配置
HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.0
  enc_act: 'gelu'
  pe_temperature: 10000
  expansion: 1.0
  depth_mult: 1
  act: 'silu'
  eval_spatial_size: [640, 640]

# 解码器配置
RTDETRTransformer:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_decoder_layers: 3
  num_queries: 300
  eval_idx: -1

# 损失函数配置
SetCriterion:
  num_classes: 80
  matcher:
    cost_class: 2
    cost_bbox: 5
    cost_giou: 2
    use_focal: True
  weight_dict:
    loss_focal: 2
    loss_bbox: 5
    loss_giou: 2
  losses: ['labels', 'boxes']
  alpha: 0.25
  gamma: 2.0

# 训练配置
epochs: 72
lr: 0.0001
batch_size: 2
weight_decay: 0.0001

# 数据配置
dataset: coco
data_root: ./data/coco2017_50
